### ISSUE TITLE
Three solutions 

### ISSUE THREAD

**Issue by lintingxue** [nikign/SE-16#10]
Develop a tool perform the following the function:
-  Install on target system : windows, osx or Linux.
- Execute the git command in terminal, like $ ToolName git push
- Trap the git error
- Detect the error key words 
  
  ```
   a. Interact with users to offer git commands suggestion
   b. Search git official website provide link help. 
   c. Ask them what task they want to do and perform the task for them . 
  ```

@YihuanDong 
@boyzhirui 
@nikign

**Comment by nikign** [comment]
Updated solutions:
1. If user wants open browser, search stack-overflow and show the results in our order
2. If user wants, send the error message to our email-bot and reply with the answer
3. Change git help to show more useful information on errors

**Comment by boyzhirui** [comment]
Solution One:
![screen shot 2016-02-26 at 9 38 10 pm](https://cloud.githubusercontent.com/assets/6066749/13370294/5aba7878-dcd1-11e5-8401-6ad0de999b16.png)

**Comment by boyzhirui** [comment]
https://github.com/nikign/Git-Helper
