### ISSUE TITLE
Try Python for interaction with git

### ISSUE THREAD

**Issue by nikign** [nikign/SE-16#12]
Commit a sample code to compare with others

**Comment by boyzhirui** [comment]
https://github.com/gitpython-developers/GitPython

# GitPython

GitPython is a python library used to interact with git repositories, high-level like git-porcelain, or low-level like git-plumbing.

It provides abstractions of git objects for easy access of repository data, and additionally allows you to access the git repository more directly using either a pure python implementation, or the faster, but more resource intensive git command implementation.

The object database implementation is optimized for handling large quantities of objects and large datasets, which is achieved by using low-level structures and data streaming.
