### ISSUE TITLE
Mockup: interaction with users

### ISSUE THREAD

**Issue by lintingxue** [nikign/SE-16#13]
Come up this solution before Tuesday meeting, 4th Feb.

**Comment by nikign** [comment]
Error will look like this:
CONFLICT (content): Merge conflict in README.md

**Comment by boyzhirui** [comment]
Conflict file like this:

# Software Engineering-2016 Spring
## We are team H
### Good Job.
<<<<<<< HEAD
Found the Problem - Feb 1/
=======
Got the Problem - Feb 1/
>>>>>>> 6d4b78df14553e611eba5fb58a359ee26d475788
======================================================= 
Software_Engineering_Project_Proposal.pdf

Implement Solution - March 1/
======================================================= 
1. Solution_summary.txt
2. Code

add comments: Linting

**Comment by YihuanDong** [comment]
First version of mock up on Google Drive: https://goo.gl/IKutNj

**Comment by YihuanDong** [comment]
Updated mock ups according to discussion on 2/9/2016 meeting.

**Comment by lintingxue** [comment]
GREAT JOB!!!

**Comment by nikign** [comment]
Looks great.
Thanks
