### ISSUE TITLE
Get and rank answers from stack-overflow

### ISSUE THREAD

**Issue by nikign** [nikign/SE-16#15]
Given an error message, search stack-overflow for that, rank the results with tf-idf and return the top 10.

**Comment by nikign** [comment]
https://github.com/hrs/python-tf-idf

**Comment by boyzhirui** [comment]
http://bit.ly/1SVhCuE

**Comment by lintingxue** [comment]
solution: rank with 0.7\* tifidf similarty + 0.6*question votes
