### ISSUE TITLE
Build our own search engine 

### ISSUE THREAD

**Issue by boyzhirui** [nikign/SE-16#16]
# Own Search Engine

Extract user's error message, use stackoverflow api, got the search result from stackoverflow, and then return the top 10 result within our search engine.

**Comment by boyzhirui** [comment]
Discuss with @lintingting about the code interface.

**Comment by nikign** [comment]
http://stackoverflow.com/questions/4216985/call-to-operating-system-to-open-url

**Comment by boyzhirui** [comment]
Use google app engine to build our search engine website.

**Comment by lintingxue** [comment]
http://stackapps.com/questions/198/py-stackexchange-an-api-wrapper-for-python

**Comment by boyzhirui** [comment]
simple dynamic website https://github.com/nikign/Git-Helper/commit/781a00550d73c94bd42a8d7a4e69be1192b8a770
