### ISSUE TITLE
Solution: Git Helper

### ISSUE THREAD

**Issue by YihuanDong** [nikign/SE-16#17]
A decision tree based git helper that respond to user and give suggestion according to their error message.

**Comment by boyzhirui** [comment]
[10 things I hate about Git](http://stevebennett.me/2012/02/24/10-things-i-hate-about-git/)

**Comment by boyzhirui** [comment]
Text Banner
http://patorjk.com/software/taag/#p=display&f=Caligraphy&t=Solution

**Comment by YihuanDong** [comment]
Finished base version,
