### ISSUE TITLE
test email handler after search results are ready

### ISSUE THREAD

**Issue by nikign** [nikign/SE-16#39]

**Comment by lintingxue** [comment]
in my googlesearch.py code, 
def google_search_engine(query):
   """
   Google search stackoverflow, return links
   """
   Links = []
   QueryStackover = 'site:stackoverflow.com %s' % query
   #print QueryStackover
   for url in search(QueryStackover, tld='es', lang='es', stop=15):
       Links.append(url)
   return Links
try to change the stop =1 then test it.

**Comment by lintingxue** [comment]
in my local, if i give the error message as "CONFLICT (content): Merge conflict in README.md.Automatic merge failed: fix conflicts and then commit the result",i print the get_email_result(errormessage), i got the following.

<div class="post-text" itemprop="text">
<p>If you mean you want the pull to overwrite local changes, doing the merge as if the working tree were clean, well, clean the working tree:</p>
<pre><code>git reset --hard
git pull
</code></pre>
<p>If there are untracked local files you could use <code>git clean</code> to remove them. Use <code>git clean -f</code> to remove untracked files, <code>-df</code> to remove untracked files and directories, and <code>-xdf</code> to remove untracked or ignored files or directories.</p>
<p>If on the other hand you want to keep the local modifications somehow, you'd use stash to hide them away before pulling, then reapply them afterwards:</p>
<pre><code>git stash
git pull
git stash pop
</code></pre>
<p>I don't think it makes any sense to literally <em>ignore</em> the changes, though - half of pull is merge, and it needs to merge the committed versions of content with the versions it fetched.</p>
</div>
