### ISSUE TITLE
Discuss about evaluation

### ISSUE THREAD

**Issue by boyzhirui** [nikign/SE-16#44]
> An evaluation plan (for how you will assess if any (all) of the above is actually useful. Note this will be your March work. Feel free to spec this out as a list of 3-4 milestones with at least one todo issue per milestone.
> http://se16.unbox.org/project/mar1.md

@nikign 
@YihuanDong 
@lintingting

**Comment by lintingxue** [comment]
# Evaluation Plan

## First two weeks:
-    Tool enhancement and testing
-    Experiment Design
-     Create repository with errors (3 common errors)
-    Split participants into three groups, assign each group with one of the solution tools to resolve the error.
- Tool evaluation by paper questionnaires
- Ask for feedback about the experiment design
- Make appointment for experiment

## Third week:
- Conduct the experiment and Collect Data (from log and survey)
- Data analysis
- Compare different solutions with solid data (time for solving the git error, user preference, etc)

## Fourth week:
- Write project report
