### ISSUE TITLE
Install third party module in Google App Engine

### ISSUE THREAD

**Issue by boyzhirui** [nikign/SE-16#48]

**Comment by boyzhirui** [comment]
http://stackoverflow.com/questions/14850853/how-to-include-third-party-python-libraries-in-google-app-engine

Try this approach
https://cloud.google.com/appengine/docs/python/tools/libraries27

**Comment by lintingxue** [comment]
Install: python model of 
sklearn 
nltk
pandas
google

**Comment by lintingxue** [comment]
google: https://breakingcode.wordpress.com/2010/06/29/google-search-python/

**Comment by lintingxue** [comment]
for parser script, you need install:
BeautifulSoup4
utils

**Comment by boyzhirui** [comment]
Packaging Python modules
https://pip.readthedocs.org/en/latest/user_guide/#requirements-files

**Comment by boyzhirui** [comment]
Install package into a specific folder:
http://stackoverflow.com/questions/2915471/install-a-python-package-into-a-different-directory-using-pip

**Comment by boyzhirui** [comment]
change nltk package to stopwords package

**Comment by boyzhirui** [comment]
Update files to install those pakcage.

**Comment by boyzhirui** [comment]
Find solutions to install sklearn on Google App Engine .

**Comment by boyzhirui** [comment]
https://scikits.appspot.com/learn

**Comment by boyzhirui** [comment]
http://www.datacommunitydc.org/blog/2013/12/a-tutorial-for-deploying-a-django-application-that-uses-numpy-and-scipy-to-google-compute-engine-using-apache2-and-modwsgi

**Comment by boyzhirui** [comment]
Natural Language Toolkit (NLTK) for App Engine
https://github.com/rutherford/nltk-gae

**Comment by boyzhirui** [comment]
Google App Engine don't support third library which uses other extensions such as C, Fortran,etc

**Comment by boyzhirui** [comment]
Finally get rid of those complex packages. Use simple tfidf.py instead.

**Comment by boyzhirui** [comment]
TypeError: expected httplib.Message, got <type 'instance'>.
https://github.com/shazow/urllib3/issues/618

**Comment by boyzhirui** [comment]
Commit https://github.com/nikign/Git-Helper/commit/b3b77924d76c894de3be29750848a9f84cab0f1f
