### ISSUE TITLE
Test Solution One

### ISSUE THREAD

**Issue by boyzhirui** [nikign/SE-16#52]
# Test Solution One
## http://git-helper-2016.appspot.com
- [x] Create test case.
- [x] Run test case.

**Comment by boyzhirui** [comment]
http://git-helper-2016.appspot.com

**Comment by lintingxue** [comment]
we r doing great job.

**Comment by boyzhirui** [comment]
Request link is so slow.... Big issue

**Comment by boyzhirui** [comment]
![screen shot 2016-02-26 at 10 55 38 pm](https://cloud.githubusercontent.com/assets/6066749/13370641/1b1eebf8-dcdc-11e5-8e7a-cce91fffa55e.png)

**Comment by boyzhirui** [comment]
test case:
alkjsf2390932490iiasdfj;

merge error
merge conflict

<div>test</div>

"'sudo test'"
'test solution one'
ååßœ∑´∑œ∑å

**Comment by boyzhirui** [comment]
Failed the last test case.

**Comment by boyzhirui** [comment]
## Fixed.
