### ISSUE TITLE
Add logging to save user data for three solution. 

### ISSUE THREAD

**Issue by lintingxue** [nikign/SE-16#60]
WEB:
1. start time
2. end time
3. error message
4. returned link
5. is helpful? (pop up window)
6. store in GAE datashore

Email:
1. google form to confirm whether it’s helpful(select submit)

Decision tree:
1. command run
2. command body
3. user input
4. command result is helpful?
@nikign @boyzhirui  @boyzhirui

**Comment by YihuanDong** [comment]
Split into three issues for people to work on simultaneously.
