### ISSUE TITLE
Add Logging to Web Solution

### ISSUE THREAD

**Issue by YihuanDong** [nikign/SE-16#63]
WEB:
1. start time
2. end time
3. error message
4. returned link
5. is helpful? (pop up window)
6. store in GAE datashore

**Comment by boyzhirui** [comment]
Finished https://github.com/nikign/Git-Helper/commit/91d432c58fbc7f83ed56647a1f419d2345d340e0

**Comment by boyzhirui** [comment]
<img width="749" alt="screen shot 2016-02-29 at 4 07 39 pm" src="https://cloud.githubusercontent.com/assets/6066749/13409001/a9bf29d0-defe-11e5-901f-2a8f61f59a14.png">
<img width="729" alt="screen shot 2016-02-29 at 4 07 18 pm" src="https://cloud.githubusercontent.com/assets/6066749/13409003/aba7b71c-defe-11e5-97bf-08d36a0eb388.png">
