### ISSUE TITLE
git commands don't work for helper

### ISSUE THREAD

**Issue by nikign** [nikign/SE-16#66]
When I try git status, log, etc. I get:
[Errno 2] No such file or directory

**Comment by YihuanDong** [comment]
This is because of the check_output() requires to split the commands into words in order to work in Mac system. I don't have a solution for this for now. Keep trying.

**Comment by YihuanDong** [comment]
Fixed on this commit: 0d6fa7f2604207d9cc2c10b653e2c9dfe2e46a06
