### ISSUE TITLE
Crawl websites to build our own database

### ISSUE THREAD

**Issue by lintingxue** [nikign/SE-16#70]

**Comment by boyzhirui** [comment]
crawl on stackoverflow website, questions are related to git errors.

**Comment by boyzhirui** [comment]
I can only crawl for about 400 results, and then be blocked by Google :(. I'll try to use stackoverflow API to see whether it works.

**Comment by boyzhirui** [comment]
I even don't know the HTTP request limit of Google. I searched online, but there is no information about this. I tried and been blocked several times.

**Comment by boyzhirui** [comment]
http://stackapps.com/questions/198/py-stackexchange-an-api-wrapper-for-python

**Comment by boyzhirui** [comment]
Help wanted:
1. run copy_files_to_GAE.py to copy GoogleSearch to git-web folder.
2. run webCrawler.py, change the Query keyword content (in line 34) before running
3. Zip all the output csv file

**Comment by boyzhirui** [comment]
- [x] git add error
- [x] git push error
- [x] git pull error
- [x] git checkout error
- [x] git merge error
- [x] git commit error

**Comment by boyzhirui** [comment]
Finish crawling all the data.
