### ISSUE TITLE
Git User Survey

### ISSUE THREAD

**Issue by YihuanDong** [nikign/SE-16#8]
Here is a link to Git User Survey in Google Form: http://goo.gl/forms/bJSxK5QbP7

Please take a look and post your thoughts below. 

@boyzhirui @lintingting @nikign

**Comment by boyzhirui** [comment]
Good Job! The form looks good.

**Comment by lintingxue** [comment]
nicely done! Thanks. i just did the survey.

**Comment by YihuanDong** [comment]
Here is the paper based questionnaire. Please take a look: https://www.sharelatex.com/project/56a18049714506014cb7b633

I added a question: "Why did you learn git?" as question 3, to get people's intention to learn Git. This may possibly affect our solutions. Please leave your comments and possible options if you agree with adding the question.

**Comment by nikign** [comment]
I think the question and its options are great.
Thanks

**Comment by lintingxue** [comment]
NICE. I am ok with it. tks

**Comment by boyzhirui** [comment]
Well done.
