### ISSUE TITLE
Relative git tool or Git command teaching methods

### ISSUE THREAD

**Issue by lintingxue** [nikign/SE-16#9]
Provide the link of some git wrapper, with which we may use as reference.

**Comment by lintingxue** [comment]
1. https://github.com/cpliakas/git-wrapper
   A PHP wrapper for github that provides a new interface for github, you can access github through their predefined commands instead of executing git commands.
2. Advanced version of 1.
   https://github.com/teqneers/PHP-Stream-Wrapper-for-Git

**Comment by boyzhirui** [comment]
https://github.com/golbin/git-commander
A git tool with an easy terminal interface.

**Comment by lintingxue** [comment]
Haaranen, Lassi, and Teemu Lehtinen. "Teaching git on the side: Version control system as a course platform." Proceedings of the 2015 ACM Conference on Innovation and Technology in Computer Science Education. ACM, 2015.

This describe how to incrementally present features of Git and incorporate them into the course workflow.

**Comment by lintingxue** [comment]
githug

http://www.tobscore.com/githug-what-is-it/

**Comment by lintingxue** [comment]
done
